# Generated by Django 2.2.14 on 2020-11-22 05:49

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField

# TODO replace migrations.AlterField by AlterSortedManyToManyField

class Migration(migrations.Migration):
    
    dependencies = [
        ('app', '0007_auto_20201117_2334'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='report',
            name='chart',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='app.Chart'),
        ),
    ]
